export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
export const SET_TEMP_TYPE_CELSIUS = 'SET_TEMP_TYPE_CELSIUS';
export const SET_TEMP_TYPE_FAHRENHEIT = 'SET_TEMP_TYPE_FAHRENHEIT';
export const FETCHING_DATA = 'FETCHING_DATA';
export const HISTORY_STATE_TO_CURRENT_STATE = 'HISTORY_STATE_TO_CURRENT_STATE';
export const ERROR_FETCH_COORDINATES = 'ERROR_FETCH_COORDINATES';